### ISSUE TITLE
Add Webmentions to blog posts

### ISSUE THREAD

**Issue by philgyford** [philgyford/django-hines#218]
And to link posts? Or would that have to go into django-ditto?

- https://indieweb.org/Webmention
- https://github.com/easy-as-python/django-webmention (receive only)
- https://github.com/beatonma/django-wm (send and receive? Requires celery and rabbitmq)
- https://github.com/bear/ronkyuu (send and receive)
- https://github.com/Ryuno-Ki/webmention-tools (send and (maybe?) receive via webmention.io)

## Tasks

- [x] Create `MentionableMixin` model:
- [x] Create `IncomingWebmention` model:
  - `time_created` (from `TimeStampedModelMixin`)
  - `time_modified` (from `TimeStampedModelMixin`)
  - `GenericForeignKey` fields to link to Post (or whatever)
  - `source_title`
  - `source_url`
  - `target_url`
  - `is_visible` boolean
  - `is_deleted` boolean (for if the source was 410 or 404 at last check)
  - `validated` boolean (if both source and target URL have been verified to exist, as [in django-wm](https://github.com/beatonma/django-wm/blob/master/mentions/models/webmention.py))?
  - `time_deleted` (ditto)
- [x] Create `OutgoingWebmention` model:
  - `time_created` (from `TimeStampedModelMixin`)
  - `time_modified` (from `TimeStampedModelMixin`)
  - `GenericForeignKey` fields to link to Post (or whatever)
  - `source_url`
  - `target_url`
  - `target_endpoint_url`
  - `status` - waiting, unreachable, target error, endpoint error, ok
  - `response_code`
- [x] Add `allow_incoming_webmentions` and `allow_outgoing_webmentions` to Post (or any model that we have them on?))?
- [ ] `OutgoingWebmentionStatus` model, as [in django-wm](https://github.com/beatonma/django-wm/blob/master/mentions/models/webmention.py)?
- [x] Generate outgoing mentions when a Post (etc) is saved
- [x] Add a 'Webmentions enabled' global settings (incoming and outgoing)
- [x] And/or a setting to set whether incoming Webmentions are automatically approved or not?
- [ ] Create a `/webmentions` endpoint
- [ ] Create a middleware to add webmention endpoint to HTTP headers, as in ronkyuu and django-wm?
- [ ] Management command for sending any unsent webmentions
- [ ] List valid, public incoming mentions on the end of a Post
- [ ] Show count of incoming mentions in list view of Posts

**Comment by philgyford** [comment]
So django-webmention only handles incoming webmentions.

django-wm requires RabbitMQ and Celery.
