### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by philgyford** [philgyford/django-hines#84]
## New server setup

* [x] Create S3 bucket for media
    * [x] Copy current `/phil/writing/resources/*` to bucket at `/weblogs/*`.
* [x] Create Heroku droplet with:
    * [x] Postgres
    * [x] Memcachier
    * [x] Sentry
* [x] Set config vars:
    * [x] `HINES_GOOGLE_ANALYTICS_ID` = `'UA-89135-1'`
* [x] Hook into Travis
* [x] Add Slack integration:
    * [x] GitHub
    * [x] Travis
    * [x] Sentry
* [x] Set up postgres backups to S3
* [x] Check postgres backups to S3 are working

## Once installed on server

* [x] Set Sites domain name.
* [x] Fetch Writing and Comments blogs
    * [x] Replace all `/writing/resources/*` URLs and image paths to `[media bucket]/weblogs/*`
    * [x] Check through recent blog posts (since Sep 2017?) for some encoding issues like `â€¦` (1 Oct 2017) and `Â£4` (3 Sep 2017).
* [x] Disable commenting
* [x] Fetch Reading.
* [x] Import:
    * [x] Twitter tweets
    * [x] Twitter favorites
    * [x] Flickr photos
    * [x] Flickr photosets
    * [x] Last.fm scrobbles
    * [x] Pinboard bookmarks
* [x] [Reset SQL sequences](https://stackoverflow.com/a/14589706/250962) for imported things
* [x] Set up Flat Pages and copy content over
    * [x] About
    * [x] Work
    * [x] Timeline
    * [x] Misc
* [x] Set up Blocks and copy content over
* [x] Set up management commands to continue to fetch:
    * [x] Twitter tweets
    * [x] Twitter favorites
    * [x] Flickr photos
    * [x] Flickr photosets
    * [x] Last.fm scrobbles
    * [x] Pinboard bookmarks
* [x] Add redirects to Redirects app based on:
    * [x] `/.htaccess`
    * [x] `/phil/.htaccess`
    * [x] Old Writing categories, to their tag equivalents

## Ready to change

* [x] Archive some pages of current site on archive.gyford.com

## Change!

* [x] Point domain at new server
* [x] Update domain of the Site in admin
* [x] Turn `PREPEND_WWW` back on in Django settings

## After domain propagated:

* [x] [Redirect all FeedBurner RSS feeds](https://create.blubrry.com/manual/syndicating-your-podcast-rss-feeds/leaving-feedburner/) to new equivalents if possible 
* [x] Check 404 error page (at least) is rendering correctly.
* [x] Archive old site
    * [x] Files
    * [x] Both databases
